#Aggregates Cancer specific p-values of sex-linked gene expression disparities into pan-cancer P-values
#Jonathan Ma

#set to your own working directory
setwd("C:/Users/Jonathan Ma/Google Drive/ExpressionSexProject/Methylation_Cbio_v2")

library(MADAM)

#read raw wilcoxon P values generated by Methyation_Cbio_analysis_publication.R
wilcP=readRDS('WilcoxonRawP_methyl.RDS')

#this table of HUGO genes is here so that you can select which genes you want to analyze
geneNames=read.table('human_genes.txt',sep="\t")

#Fisher's method to aggregate p-values
MetaPs=fisher.method(wilcP,na.rm=T)
entrezIdList=geneNames[,2]
hugoGeneList=geneNames[,3]
rowNames=rownames(wilcP)
allEntrezIds=integer(0)
for(i in 1:nrow(wilcP))
{
  currentHugo=rowNames[i]
  currentEntrezId=entrezIdList[hugoGeneList==currentHugo]
  currentEntrezId=currentEntrezId[1]
  allEntrezIds=c(allEntrezIds,currentEntrezId)
}
MetaPs=cbind(allEntrezIds,MetaPs)
write.table(MetaPs,"Meta.Ps_methyl_entrez_6.21.14.txt",col.names=NA,sep="\t")
sum(MetaPs$p.adj<0.05)
