#Analyzes methylation data downloaded from Cbioportal
#computes p-values, median difference estimates, and fold changes of sex differences in methylation for individual cancers
#Jonathan Ma
#6.19.2014

#set to your desired working directory
setwd("C:/Users/admin/Google Drive/ExpressionSexProject/Methylation_Cbio_v2")


#data not available on cbioportal for READ, COAD, and LGG
#note: filenames must be of the form [cancer-abbreviation]_methylation.RDS
fileNames=dir(pattern="methylation.RDS")
allCancerTypes=gsub("([a-z]+)_methylation.RDS","\\1",fileNames)
allCancerTypes=toupper(allCancerTypes)

#since clinical data from cbioportal itself is sparse, need to use master TCGA clinical data file
clinical.data=readRDS('MasterClinical.RDS')
#convert clinical data barcodes to standard format by making them uppercase
clinical.data$barcode <- toupper(clinical.data$barcode)

#initialize matrices to contain wilcoxon P-values and wilcoxon estimated median differences for male and female
#wilc.mat: rows=probes, 2 columns (1 for est, 1 for p values)
#each column of wilc.mat is a tissue type
#each row of wilc.mat is a gene in the mutation data file (and each data file has the same genes)
wilcP <- matrix(c(1,0),nrow=nrow(readRDS(fileNames[1])),ncol=length(fileNames),byrow=T)
wilcEst <- matrix(c(1,0),nrow=nrow(readRDS(fileNames[1])),ncol=length(fileNames),byrow=T)
all.methyl.data=readRDS(fileNames[1])
colnames(all.methyl.data)=gsub("TCGA.([A-Z0-9]+).([A-Z0-9]+)","TCGA-\\1-\\2",colnames(all.methyl.data))
removeRowsList=c(1)
removeRowsList=removeRowsList[-1]
naValues=logical(0)
naIndexes=integer(0)

naRows=logical(0)
currentRowNAs=logical(0)
currentRowNAValues=integer(0)
naRowIndexes=integer(0)
overallNARowIndexes=integer(0)

for(i in 1:length(fileNames))
{ 
  #record rows with NA's, which will not be used in analysis
  methyl.data=readRDS(fileNames[i])
  colnames(methyl.data)=gsub("TCGA.([A-Z0-9]+).([A-Z0-9]+)","TCGA-\\1-\\2",colnames(methyl.data))
  #filter to only include barcodes for which we have clinical data
  methyl.data=methyl.data[,colnames(methyl.data)%in%clinical.data$barcode]
  tissue.clinical=clinical.data[clinical.data$barcode%in%colnames(methyl.data),]
  
  for(currentRow in 1:nrow(methyl.data))
  {
    currentRowNAs=is.na(methyl.data[currentRow,])
    currentRowNAValues=c(1:ncol(methyl.data))
    currentRowNAValues=currentRowNAValues[currentRowNAs]
    naRows=c(naRows,length(currentRowNAValues)==ncol(methyl.data))
  }
  
  naRowIndexes=c(1:nrow(methyl.data)) #rows that are all NA's for the current methyl.data
  naRowIndexes=naRowIndexes[naRows]
  overallNARowIndexes=c(overallNARowIndexes,naRowIndexes)
  overallNARowIndexes=unique(overallNARowIndexes)
  overallNARowIndexes=sort(naRowIndexes,decreasing=T)
  
  
  cat("\nComputing wilcoxon test for cancer type: ",allCancerTypes[i])
  #loop over all genes in methyl.data, and perform wilcoxon rank-sum test if the row is not NA
  for(j in 1:nrow(methyl.data))
  {
    numUnique=0
    numUnique=length(unique(methyl.data[j,]))
    if(numUnique>2 && !(j %in% naRowIndexes))
    {
      cat("\nAnalyzing gene ",j," of ",nrow(methyl.data)," in ",allCancerTypes[i])
      temp.dataframe=data.frame(methyl.data[j,],tissue.clinical$gender)
      colnames(temp.dataframe)=c("copynumbers","gender")
      twilc=wilcox.test(temp.dataframe$copynumbers~temp.dataframe$gender,conf.int=T)
      wilcEst[j,i]=twilc$est
      wilcP[j,i]=twilc$p.value
    }
    else
    {
      removeRowsList=c(removeRowsList,j)
    }
  }
  
  #save the wilcoxon estimate and 
  saveRDS(wilcEst[,i],paste0(allCancerTypes[i],"_methyl_wilcEst_Unremoved.RDS",sep=""))
  saveRDS(wilcP[,i],paste0(allCancerTypes[i],"_methyl_wilcP_Unremoved.RDS",sep=""))
}

colnames(wilcEst)=allCancerTypes
colnames(wilcP)=allCancerTypes
rownames(wilcEst)=rownames(all.methyl.data)
rownames(wilcP)=rownames(all.methyl.data)

#remove rows with NA's, as those P-values are irrelevant
removeRowsList=c(overallNARowIndexes,removeRowsList)
removeRowsList=unique(removeRowsList) #each row can only be removed once
removeRowsList=sort(removeRowsList,decreasing=T) # remove backwards
all.methyl.data=all.methyl.data[-removeRowsList,]
wilcEst=wilcEst[-removeRowsList,]
wilcP=wilcP[-removeRowsList,]

#save raw p-values and median difference estimations
saveRDS(wilcEst,"MedianDiffEstimate_methyl_Removed.RDS")
saveRDS(wilcP,"WilcoxonRawP_methyl_Removed.RDS")


#adjust p-values using benjamini-hochberg method
adj.wilcP.vector=c(wilcP)
adj.wilcP.vector=p.adjust(adj.wilcP.vector,method='fdr')
adj.wilcP=matrix(adj.wilcP.vector,ncol=ncol(wilcP),byrow=F)
rownames(adj.wilcP)=rownames(wilcP)
colnames(adj.wilcP)=colnames(wilcP)
saveRDS(adj.wilcP,"WilcoxonAdjustedP_methyl.RDS")

#Fisher's method - tumors & normals
# combine the p values generated by the wilcoxon test
MetaPs=fisher.method(wilcP,na.rm=T)
write.table(MetaPs,"Meta.Ps_methyl_6.20.14.txt",col.names=NA,sep="\t")
